version: '2'
services:
  sampleservicejhipster-app:
    image: sampleservicejhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sampleservicejhipster-postgresql:5432/SampleServiceJHipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://sampleservicejhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sampleservicejhipster-elasticsearch:9200
  sampleservicejhipster-postgresql:
    extends:
      file: postgresql.yml
      service: sampleservicejhipster-postgresql
  sampleservicejhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sampleservicejhipster-elasticsearch
